#!/usr/bin/env bash
# scripts/GenerateConfig.sh
# Resolve URLs from env/defaults and write runtime config files into the
# spec bind-mount layout under ${STACK_BINDMOUNTROOT}/OpenRPort/.
# Idempotent.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "$0")/.." && pwd))"
ENV_FILE="${REPO_ROOT}/.env"
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a
else echo "[WARN] No .env file found - using environment as-is."; fi

bash "${REPO_ROOT}/scripts/ValidateEnv.sh"

STACK_BINDMOUNTROOT="${STACK_BINDMOUNTROOT:-/mnt/data/docker/stacks}"
ROOT="${STACK_BINDMOUNTROOT}/OpenRPort"

MODE="${OPENRPORT_DEPLOYMENT_MODE:-subpath}"
SERVER_BASE="${OPENRPORT_SERVER_BASE_PATH:-/}"
PAIRING_BASE="${OPENRPORT_PAIRING_BASE_PATH:-/pairing}"
UI_BASE="${OPENRPORT_UI_BASE_PATH:-/ui}"
BINARIES_BASE="${OPENRPORT_BINARIES_BASE_PATH:-/binaries}"

# Per-service internal listen ports (config files live inside the container
# so these are the in-container ports, not host-side publish ports).
SERVER_API_INTERNAL_PORT="${SERVER_API_INTERNAL_PORT:-8080}"
SERVER_CLIENT_INTERNAL_PORT="${SERVER_CLIENT_INTERNAL_PORT:-8081}"
PAIRING_INTERNAL_PORT="${PAIRING_INTERNAL_PORT:-9978}"

# Host-side publish ports - used only to compute fallback PUBLIC URLs when
# OPENRPORT_*_PUBLIC_URL is empty (i.e. local testing without an edge proxy).
SERVER_API_PUBLISH_PORT="${SERVER_API_PUBLISH_PORT:-8080}"
SERVER_CLIENT_PUBLISH_PORT="${SERVER_CLIENT_PUBLISH_PORT:-8081}"
PAIRING_PUBLISH_PORT="${PAIRING_PUBLISH_PORT:-9978}"
UI_PUBLISH_PORT="${UI_PUBLISH_PORT:-3000}"

# In local mode each service is fronted on its own host port. Pairing also
# serves the static binaries under ${BINARIES_BASE} on the same port.
SERVER_URL="${OPENRPORT_SERVER_PUBLIC_URL:-http://localhost:${SERVER_CLIENT_PUBLISH_PORT}}"
PAIRING_URL="${OPENRPORT_PAIRING_PUBLIC_URL:-http://localhost:${PAIRING_PUBLISH_PORT}}"
UI_URL="${OPENRPORT_UI_PUBLIC_URL:-http://localhost:${UI_PUBLISH_PORT}}"
BINARIES_URL="${OPENRPORT_BINARIES_PUBLIC_URL:-http://localhost:${PAIRING_PUBLISH_PORT}${BINARIES_BASE}}"

echo ""
echo "==> Generating runtime config under ${ROOT}"
echo "    Deployment mode : $MODE"
echo "    Server URL      : $SERVER_URL"
echo "    Pairing URL     : $PAIRING_URL"
echo "    UI URL          : $UI_URL"
echo "    Binaries URL    : $BINARIES_URL"

# ── Tier directories ───────────────────────────────────────────────────────
mkdir -p \
  "${ROOT}/Server/Config"   "${ROOT}/Server/Data"   "${ROOT}/Server/Logs"   \
  "${ROOT}/Pairing/Config"  "${ROOT}/Pairing/Logs"                          \
  "${ROOT}/UI"              "${ROOT}/UI/Logs"                               \
  "${ROOT}/Binaries/Data"

# ── rportd.conf ────────────────────────────────────────────────────────────
RPORTD_CONF="${ROOT}/Server/Config/rportd.conf"
cat > "$RPORTD_CONF" <<EOF
# Generated by GenerateConfig.sh - do not edit manually.
# Re-run: make generate-config

[server]
address     = "0.0.0.0:${SERVER_CLIENT_INTERNAL_PORT}"
url         = "${SERVER_URL}"
data_dir    = "/var/lib/rport"
key_seed    = "${RPORTD_KEY_SEED}"
auth        = "${RPORTD_CLIENT_AUTH}"
pairing_url = "${PAIRING_URL}"
auth_multiuse_creds = true

[api]
address     = "0.0.0.0:${SERVER_API_INTERNAL_PORT}"
auth        = "${RPORTD_API_USER:-admin}:${RPORTD_API_PASSWORD}"
jwt_secret  = "${RPORTD_JWT_SECRET}"
cors        = ["${RPORTD_CORS_ORIGINS:-*}"]

[logging]
log_file    = "/var/log/rport/rportd.log"
log_level   = "info"
EOF
echo "    Wrote: Server/Config/rportd.conf"

# ── pairing config.toml ────────────────────────────────────────────────────
PAIRING_CONF="${ROOT}/Pairing/Config/config.toml"
cat > "$PAIRING_CONF" <<EOF
# Generated by GenerateConfig.sh - do not edit manually.
[server]
  address = "0.0.0.0:${PAIRING_INTERNAL_PORT}"
  url     = "${PAIRING_URL}"
EOF
echo "    Wrote: Pairing/Config/config.toml"

# ── UI runtime env (informational; baked into image at build) ─────────────
UI_RUNTIME="${ROOT}/UI/runtime.env"
cat > "$UI_RUNTIME" <<EOF
# Generated by GenerateConfig.sh - sourced into UI container at runtime.
NUXT_PUBLIC_API_URL=${SERVER_URL}
NUXT_APP_BASE_URL=${UI_BASE}
EOF
echo "    Wrote: UI/runtime.env"

echo ""
echo "==> Config generation complete."
