#!/usr/bin/env bash
# scripts/GenerateConfig.sh
# Resolve URLs from env/defaults and write runtime config files into the
# spec bind-mount layout under ${STACK_BINDMOUNTROOT}/OpenRPort/.
# Idempotent.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "$0")/.." && pwd))"
ENV_FILE="${REPO_ROOT}/.env"
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a
else echo "[WARN] No .env file found - using environment as-is."; fi

bash "${REPO_ROOT}/scripts/ValidateEnv.sh"

STACK_BINDMOUNTROOT="${STACK_BINDMOUNTROOT:-/mnt/data/docker/stacks}"
ROOT="${STACK_BINDMOUNTROOT}/OpenRPort"

MODE="${OPENRPORT_DEPLOYMENT_MODE:-subpath}"
SERVER_BASE="${OPENRPORT_SERVER_BASE_PATH:-/}"
PAIRING_BASE="${OPENRPORT_PAIRING_BASE_PATH:-/pairing}"
UI_BASE="${OPENRPORT_UI_BASE_PATH:-/ui}"
BINARIES_BASE="${OPENRPORT_BINARIES_BASE_PATH:-/binaries}"

# Per-service listen ports. With network_mode: host these are also the
# host-side ports -- there is no publish/internal distinction.
SERVER_API_INTERNAL_PORT="${SERVER_API_INTERNAL_PORT:-8080}"
SERVER_CLIENT_INTERNAL_PORT="${SERVER_CLIENT_INTERNAL_PORT:-8081}"
PAIRING_INTERNAL_PORT="${PAIRING_INTERNAL_PORT:-38102}"
UI_INTERNAL_PORT="${UI_INTERNAL_PORT:-38103}"

# Per-service bind addresses. Each falls back to OPENRPORT_BIND_ADDRESS,
# which itself falls back to 0.0.0.0. On a VPS where nginx is collocated
# with the stack and proxies all traffic, set OPENRPORT_*_BIND_ADDRESS to
# 127.0.0.1 to keep the service loopback-only while still allowing the
# tunnel port pool (used_ports) to be reachable from agents on whichever
# interface is configured for the chisel listener.
BIND_DEFAULT="${OPENRPORT_BIND_ADDRESS:-0.0.0.0}"
SERVER_API_BIND="${OPENRPORT_SERVER_API_BIND_ADDRESS:-$BIND_DEFAULT}"
SERVER_CLIENT_BIND="${OPENRPORT_SERVER_CLIENT_BIND_ADDRESS:-$BIND_DEFAULT}"
PAIRING_BIND="${OPENRPORT_PAIRING_BIND_ADDRESS:-$BIND_DEFAULT}"

# Tunnel port pool baked into rportd.conf [server]. used_ports is the pool
# rportd allocates from for reverse tunnels; excluded_ports carves holes
# inside that pool. Defaults match upstream rportd.
TUNNEL_USED_PORTS="${OPENRPORT_TUNNEL_USED_PORTS:-38200-38400}"
TUNNEL_EXCLUDED_PORTS="${OPENRPORT_TUNNEL_EXCLUDED_PORTS:-1-1024}"

# Convert comma-separated lists into TOML array form: 'a','b','c'
toml_array() {
  local IFS=,
  local out=""
  for item in $1; do
    item="${item#"${item%%[![:space:]]*}"}"
    item="${item%"${item##*[![:space:]]}"}"
    [ -z "$item" ] && continue
    [ -n "$out" ] && out="$out, "
    out="$out'$item'"
  done
  printf '%s' "$out"
}
TUNNEL_USED_PORTS_TOML=$(toml_array "$TUNNEL_USED_PORTS")
TUNNEL_EXCLUDED_PORTS_TOML=$(toml_array "$TUNNEL_EXCLUDED_PORTS")

# In local mode each service is fronted on its own host port. Pairing also
# serves the static binaries under ${BINARIES_BASE} on the same port.
# SERVER_URL is the agent-facing URL (port 8081) baked into rportd.conf and
# install scripts; SERVER_API_URL is the browser-facing API URL (port 8080)
# emitted into the UI runtime env. They diverge in standalone local testing.
SERVER_URL="${OPENRPORT_SERVER_PUBLIC_URL:-http://localhost:${SERVER_CLIENT_INTERNAL_PORT}}"
SERVER_API_URL="${OPENRPORT_SERVER_API_URL:-${OPENRPORT_SERVER_PUBLIC_URL:-http://localhost:${SERVER_API_INTERNAL_PORT}}}"
PAIRING_URL="${OPENRPORT_PAIRING_PUBLIC_URL:-http://localhost:${PAIRING_INTERNAL_PORT}}"
UI_URL="${OPENRPORT_UI_PUBLIC_URL:-http://localhost:${UI_INTERNAL_PORT}}"
BINARIES_URL="${OPENRPORT_BINARIES_PUBLIC_URL:-http://localhost:${PAIRING_INTERNAL_PORT}${BINARIES_BASE}}"

echo ""
echo "==> Generating runtime config under ${ROOT}"
echo "    Deployment mode : $MODE"
echo "    Server URL      : $SERVER_URL"
echo "    Server API URL  : $SERVER_API_URL"
echo "    Pairing URL     : $PAIRING_URL"
echo "    UI URL          : $UI_URL"
echo "    Binaries URL    : $BINARIES_URL"
echo "    Bind: api=${SERVER_API_BIND} client=${SERVER_CLIENT_BIND} pairing=${PAIRING_BIND}"
echo "    Tunnels: used=${TUNNEL_USED_PORTS} excluded=${TUNNEL_EXCLUDED_PORTS}"

# ── Tier directories ───────────────────────────────────────────────────────
mkdir -p \
  "${ROOT}/Server/Config"   "${ROOT}/Server/Data"   "${ROOT}/Server/Logs"   \
  "${ROOT}/Pairing/Config"  "${ROOT}/Pairing/Logs"                          \
  "${ROOT}/UI"              "${ROOT}/UI/Logs"                               \
  "${ROOT}/Binaries/Data"

# ── rportd.conf ────────────────────────────────────────────────────────────
RPORTD_CONF="${ROOT}/Server/Config/rportd.conf"
cat > "$RPORTD_CONF" <<EOF
# Generated by GenerateConfig.sh - do not edit manually.
# Re-run: make generate-config

[server]
address        = "${SERVER_CLIENT_BIND}:${SERVER_CLIENT_INTERNAL_PORT}"
url            = "${SERVER_URL}"
data_dir       = "/var/lib/rport"
key_seed       = "${RPORTD_KEY_SEED}"
auth           = "${RPORTD_CLIENT_AUTH}"
pairing_url    = "${PAIRING_URL}"
used_ports     = [${TUNNEL_USED_PORTS_TOML}]
excluded_ports = [${TUNNEL_EXCLUDED_PORTS_TOML}]
auth_multiuse_creds = true

[api]
address     = "${SERVER_API_BIND}:${SERVER_API_INTERNAL_PORT}"
auth        = "${RPORTD_API_USER:-admin}:${RPORTD_API_PASSWORD}"
jwt_secret  = "${RPORTD_JWT_SECRET}"
cors        = ["${RPORTD_CORS_ORIGINS:-*}"]

[logging]
log_file    = "/var/log/rport/rportd.log"
log_level   = "info"
EOF

# ── Optional [plus-plugin]/[plus-oauth] section (OIDC) ────────────────────
# Activated only when RPORT_OIDC_ISSUER_URL is set. The plugin .so is built
# into the Server image at /usr/local/lib/rport/rport-plus.so; override with
# RPORT_PLUS_PLUGIN_PATH when bind-mounting an external build.
#
# Endpoint resolution:
#   1. Explicit RPORT_OIDC_AUTHORIZE_URL/TOKEN_URL/JWKS_URL win.
#   2. Otherwise we attempt OIDC discovery: RPORT_OIDC_ISSUER_URL is treated
#      as either the issuer (we append /.well-known/openid-configuration) or
#      as the discovery URL itself if it already ends in /.well-known/...
#      The discovery doc is fetched with curl+jq.
#   3. If discovery fails, we abort with a clear error so the operator can
#      either fix network access or supply explicit *_URL overrides.
if [ -n "${RPORT_OIDC_ISSUER_URL:-}" ]; then
  PLUGIN_PATH="${RPORT_PLUS_PLUGIN_PATH:-/usr/local/lib/rport/rport-plus.so}"
  OIDC_REDIRECT="${RPORT_OIDC_REDIRECT_URI:-${UI_URL}/auth/callback}"
  case "${RPORT_OIDC_ALLOW_LOCAL_LOGIN:-false}" in
    1|true|TRUE|True|yes|YES) OIDC_ALLOW_LOCAL="true" ;;
    *) OIDC_ALLOW_LOCAL="false" ;;
  esac

  _ISSUER_RAW="${RPORT_OIDC_ISSUER_URL%/}"
  case "$_ISSUER_RAW" in
    */.well-known/openid-configuration)
      _DISCOVERY_URL="$_ISSUER_RAW"
      _ISSUER_BASE="${_ISSUER_RAW%/.well-known/openid-configuration}"
      ;;
    *)
      _ISSUER_BASE="$_ISSUER_RAW"
      _DISCOVERY_URL="${_ISSUER_BASE}/.well-known/openid-configuration"
      ;;
  esac

  OIDC_AUTHZ="${RPORT_OIDC_AUTHORIZE_URL:-}"
  OIDC_TOKEN="${RPORT_OIDC_TOKEN_URL:-}"
  OIDC_JWKS="${RPORT_OIDC_JWKS_URL:-}"

  if [ -z "$OIDC_AUTHZ" ] || [ -z "$OIDC_TOKEN" ] || [ -z "$OIDC_JWKS" ]; then
    if ! command -v jq >/dev/null 2>&1; then
      echo "    [ERROR] jq is required for OIDC discovery; install jq or set RPORT_OIDC_AUTHORIZE_URL/_TOKEN_URL/_JWKS_URL explicitly" >&2
      exit 1
    fi
    echo "    Discovering OIDC endpoints from ${_DISCOVERY_URL}"
    _DISCO_DOC=$(curl -fsS --max-time 10 "$_DISCOVERY_URL" 2>/dev/null) || {
      echo "    [ERROR] OIDC discovery failed (curl ${_DISCOVERY_URL}); set RPORT_OIDC_AUTHORIZE_URL/_TOKEN_URL/_JWKS_URL to bypass" >&2
      exit 1
    }
    OIDC_AUTHZ="${OIDC_AUTHZ:-$(printf '%s' "$_DISCO_DOC" | jq -er '.authorization_endpoint')}" || {
      echo "    [ERROR] OIDC discovery doc missing authorization_endpoint" >&2; exit 1; }
    OIDC_TOKEN="${OIDC_TOKEN:-$(printf '%s' "$_DISCO_DOC" | jq -er '.token_endpoint')}" || {
      echo "    [ERROR] OIDC discovery doc missing token_endpoint" >&2; exit 1; }
    OIDC_JWKS="${OIDC_JWKS:-$(printf '%s' "$_DISCO_DOC" | jq -er '.jwks_uri')}" || {
      echo "    [ERROR] OIDC discovery doc missing jwks_uri" >&2; exit 1; }
  fi
  cat >> "$RPORTD_CONF" <<EOF

[plus-plugin]
plugin_path = "${PLUGIN_PATH}"

[plus-oauth]
provider             = "${RPORT_OIDC_PROVIDER:-oidc}"
authorize_url        = "${OIDC_AUTHZ}"
token_url            = "${OIDC_TOKEN}"
redirect_uri         = "${OIDC_REDIRECT}"
client_id            = "${RPORT_OIDC_CLIENT_ID:?RPORT_OIDC_CLIENT_ID required when RPORT_OIDC_ISSUER_URL is set}"
client_secret        = "${RPORT_OIDC_CLIENT_SECRET:?RPORT_OIDC_CLIENT_SECRET required when RPORT_OIDC_ISSUER_URL is set}"
jwks_url             = "${OIDC_JWKS}"
username_claim       = "${RPORT_OIDC_USERNAME_CLAIM:-preferred_username}"
permitted_user_match = "${RPORT_OIDC_PERMITTED_USER_MATCH:-.*}"
allow_local_login    = ${OIDC_ALLOW_LOCAL}
EOF
  echo "    Wrote: Server/Config/rportd.conf (with [plus-oauth] -> ${_ISSUER_BASE})"
  echo "      authorize_url = ${OIDC_AUTHZ}"
  echo "      token_url     = ${OIDC_TOKEN}"
  echo "      jwks_url      = ${OIDC_JWKS}"
else
  echo "    Wrote: Server/Config/rportd.conf"
fi

# ── pairing config.toml ────────────────────────────────────────────────────
# Download endpoints baked into rendered installer scripts. Empty values fall
# back to upstream openrport.io defaults inside the pairing service. Point
# these at this stack's own /binaries mirror only after confirming it serves
# the upstream "latest.php?arch=..." URL pattern.
PAIRING_DL_BINARIES="${OPENRPORT_PAIRING_DOWNLOADS_BINARIES_BASE_URL:-}"
PAIRING_DL_TACO="${OPENRPORT_PAIRING_DOWNLOADS_TACO_BASE_URL:-}"
PAIRING_DL_REPO="${OPENRPORT_PAIRING_DOWNLOADS_REPO_BASE_URL:-}"
PAIRING_DL_RELEASE="${OPENRPORT_PAIRING_DOWNLOADS_RELEASE:-stable}"
PAIRING_CONF="${ROOT}/Pairing/Config/config.toml"
cat > "$PAIRING_CONF" <<EOF
# Generated by GenerateConfig.sh - do not edit manually.
[server]
  address = "${PAIRING_BIND}:${PAIRING_INTERNAL_PORT}"
  url     = "${PAIRING_URL}"

[downloads]
  binaries_base_url = "${PAIRING_DL_BINARIES}"
  taco_base_url     = "${PAIRING_DL_TACO}"
  repo_base_url     = "${PAIRING_DL_REPO}"
  release           = "${PAIRING_DL_RELEASE}"
EOF
echo "    Wrote: Pairing/Config/config.toml"
echo "      downloads.binaries = ${PAIRING_DL_BINARIES}"
echo "      downloads.taco     = ${PAIRING_DL_TACO}"
echo "      downloads.repo     = ${PAIRING_DL_REPO}"
echo "      downloads.release  = ${PAIRING_DL_RELEASE}"

# ── UI runtime env (informational; baked into image at build) ─────────────
UI_RUNTIME="${ROOT}/UI/runtime.env"
cat > "$UI_RUNTIME" <<EOF
# Generated by GenerateConfig.sh - sourced into UI container at runtime.
NUXT_PUBLIC_API_URL=${SERVER_API_URL}
NUXT_APP_BASE_URL=${UI_BASE}
NUXT_PUBLIC_AUTH_MODE=${OPENRPORT_UI_AUTH_MODE:-both}
EOF
echo "    Wrote: UI/runtime.env"

echo ""
echo "==> Config generation complete."
