#!/usr/bin/env bash
# scripts/GenerateConfig.sh
# Resolve URLs from env/defaults and write runtime config files into the
# spec bind-mount layout under ${STACK_BINDMOUNTROOT}/OpenRPort/.
# Idempotent.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "$0")/.." && pwd))"
ENV_FILE="${REPO_ROOT}/.env"
if [ -f "$ENV_FILE" ]; then set -a; . "$ENV_FILE"; set +a
else echo "[WARN] No .env file found - using environment as-is."; fi

bash "${REPO_ROOT}/scripts/ValidateEnv.sh"

STACK_BINDMOUNTROOT="${STACK_BINDMOUNTROOT:-/mnt/data/docker/stacks}"
ROOT="${STACK_BINDMOUNTROOT}/OpenRPort"

MODE="${OPENRPORT_DEPLOYMENT_MODE:-subpath}"
SERVER_BASE="${OPENRPORT_SERVER_BASE_PATH:-/}"
PAIRING_BASE="${OPENRPORT_PAIRING_BASE_PATH:-/pairing}"
UI_BASE="${OPENRPORT_UI_BASE_PATH:-/ui}"
BINARIES_BASE="${OPENRPORT_BINARIES_BASE_PATH:-/binaries}"

# Per-service internal listen ports (config files live inside the container
# so these are the in-container ports, not host-side publish ports).
SERVER_API_INTERNAL_PORT="${SERVER_API_INTERNAL_PORT:-8080}"
SERVER_CLIENT_INTERNAL_PORT="${SERVER_CLIENT_INTERNAL_PORT:-8081}"
PAIRING_INTERNAL_PORT="${PAIRING_INTERNAL_PORT:-9978}"

# Host-side publish ports - used only to compute fallback PUBLIC URLs when
# OPENRPORT_*_PUBLIC_URL is empty (i.e. local testing without an edge proxy).
SERVER_API_PUBLISH_PORT="${SERVER_API_PUBLISH_PORT:-8080}"
SERVER_CLIENT_PUBLISH_PORT="${SERVER_CLIENT_PUBLISH_PORT:-8081}"
PAIRING_PUBLISH_PORT="${PAIRING_PUBLISH_PORT:-9978}"
UI_PUBLISH_PORT="${UI_PUBLISH_PORT:-3000}"

# In local mode each service is fronted on its own host port. Pairing also
# serves the static binaries under ${BINARIES_BASE} on the same port.
SERVER_URL="${OPENRPORT_SERVER_PUBLIC_URL:-http://localhost:${SERVER_CLIENT_PUBLISH_PORT}}"
PAIRING_URL="${OPENRPORT_PAIRING_PUBLIC_URL:-http://localhost:${PAIRING_PUBLISH_PORT}}"
UI_URL="${OPENRPORT_UI_PUBLIC_URL:-http://localhost:${UI_PUBLISH_PORT}}"
BINARIES_URL="${OPENRPORT_BINARIES_PUBLIC_URL:-http://localhost:${PAIRING_PUBLISH_PORT}${BINARIES_BASE}}"

echo ""
echo "==> Generating runtime config under ${ROOT}"
echo "    Deployment mode : $MODE"
echo "    Server URL      : $SERVER_URL"
echo "    Pairing URL     : $PAIRING_URL"
echo "    UI URL          : $UI_URL"
echo "    Binaries URL    : $BINARIES_URL"

# ── Tier directories ───────────────────────────────────────────────────────
mkdir -p \
  "${ROOT}/Server/Config"   "${ROOT}/Server/Data"   "${ROOT}/Server/Logs"   \
  "${ROOT}/Pairing/Config"  "${ROOT}/Pairing/Logs"                          \
  "${ROOT}/UI"              "${ROOT}/UI/Logs"                               \
  "${ROOT}/Binaries/Data"

# ── rportd.conf ────────────────────────────────────────────────────────────
RPORTD_CONF="${ROOT}/Server/Config/rportd.conf"
cat > "$RPORTD_CONF" <<EOF
# Generated by GenerateConfig.sh - do not edit manually.
# Re-run: make generate-config

[server]
address     = "0.0.0.0:${SERVER_CLIENT_INTERNAL_PORT}"
url         = "${SERVER_URL}"
data_dir    = "/var/lib/rport"
key_seed    = "${RPORTD_KEY_SEED}"
auth        = "${RPORTD_CLIENT_AUTH}"
pairing_url = "${PAIRING_URL}"
auth_multiuse_creds = true

[api]
address     = "0.0.0.0:${SERVER_API_INTERNAL_PORT}"
auth        = "${RPORTD_API_USER:-admin}:${RPORTD_API_PASSWORD}"
jwt_secret  = "${RPORTD_JWT_SECRET}"
cors        = ["${RPORTD_CORS_ORIGINS:-*}"]

[logging]
log_file    = "/var/log/rport/rportd.log"
log_level   = "info"
EOF

# ── Optional [plus-plugin]/[plus-oauth] section (OIDC) ────────────────────
# Activated only when RPORT_OIDC_ISSUER_URL is set. The plugin .so is built
# into the Server image at /usr/local/lib/rport/rport-plus.so; override with
# RPORT_PLUS_PLUGIN_PATH when bind-mounting an external build.
#
# Endpoint resolution:
#   1. Explicit RPORT_OIDC_AUTHORIZE_URL/TOKEN_URL/JWKS_URL win.
#   2. Otherwise we attempt OIDC discovery: RPORT_OIDC_ISSUER_URL is treated
#      as either the issuer (we append /.well-known/openid-configuration) or
#      as the discovery URL itself if it already ends in /.well-known/...
#      The discovery doc is fetched with curl+jq.
#   3. If discovery fails, we abort with a clear error so the operator can
#      either fix network access or supply explicit *_URL overrides.
if [ -n "${RPORT_OIDC_ISSUER_URL:-}" ]; then
  PLUGIN_PATH="${RPORT_PLUS_PLUGIN_PATH:-/usr/local/lib/rport/rport-plus.so}"
  OIDC_REDIRECT="${RPORT_OIDC_REDIRECT_URI:-${SERVER_URL}/oauth/callback}"

  _ISSUER_RAW="${RPORT_OIDC_ISSUER_URL%/}"
  case "$_ISSUER_RAW" in
    */.well-known/openid-configuration)
      _DISCOVERY_URL="$_ISSUER_RAW"
      _ISSUER_BASE="${_ISSUER_RAW%/.well-known/openid-configuration}"
      ;;
    *)
      _ISSUER_BASE="$_ISSUER_RAW"
      _DISCOVERY_URL="${_ISSUER_BASE}/.well-known/openid-configuration"
      ;;
  esac

  OIDC_AUTHZ="${RPORT_OIDC_AUTHORIZE_URL:-}"
  OIDC_TOKEN="${RPORT_OIDC_TOKEN_URL:-}"
  OIDC_JWKS="${RPORT_OIDC_JWKS_URL:-}"

  if [ -z "$OIDC_AUTHZ" ] || [ -z "$OIDC_TOKEN" ] || [ -z "$OIDC_JWKS" ]; then
    if ! command -v jq >/dev/null 2>&1; then
      echo "    [ERROR] jq is required for OIDC discovery; install jq or set RPORT_OIDC_AUTHORIZE_URL/_TOKEN_URL/_JWKS_URL explicitly" >&2
      exit 1
    fi
    echo "    Discovering OIDC endpoints from ${_DISCOVERY_URL}"
    _DISCO_DOC=$(curl -fsS --max-time 10 "$_DISCOVERY_URL" 2>/dev/null) || {
      echo "    [ERROR] OIDC discovery failed (curl ${_DISCOVERY_URL}); set RPORT_OIDC_AUTHORIZE_URL/_TOKEN_URL/_JWKS_URL to bypass" >&2
      exit 1
    }
    OIDC_AUTHZ="${OIDC_AUTHZ:-$(printf '%s' "$_DISCO_DOC" | jq -er '.authorization_endpoint')}" || {
      echo "    [ERROR] OIDC discovery doc missing authorization_endpoint" >&2; exit 1; }
    OIDC_TOKEN="${OIDC_TOKEN:-$(printf '%s' "$_DISCO_DOC" | jq -er '.token_endpoint')}" || {
      echo "    [ERROR] OIDC discovery doc missing token_endpoint" >&2; exit 1; }
    OIDC_JWKS="${OIDC_JWKS:-$(printf '%s' "$_DISCO_DOC" | jq -er '.jwks_uri')}" || {
      echo "    [ERROR] OIDC discovery doc missing jwks_uri" >&2; exit 1; }
  fi
  cat >> "$RPORTD_CONF" <<EOF

[plus-plugin]
plugin_path = "${PLUGIN_PATH}"

[plus-oauth]
provider             = "${RPORT_OIDC_PROVIDER:-oidc}"
authorize_url        = "${OIDC_AUTHZ}"
token_url            = "${OIDC_TOKEN}"
redirect_uri         = "${OIDC_REDIRECT}"
client_id            = "${RPORT_OIDC_CLIENT_ID:?RPORT_OIDC_CLIENT_ID required when RPORT_OIDC_ISSUER_URL is set}"
client_secret        = "${RPORT_OIDC_CLIENT_SECRET:?RPORT_OIDC_CLIENT_SECRET required when RPORT_OIDC_ISSUER_URL is set}"
jwks_url             = "${OIDC_JWKS}"
username_claim       = "${RPORT_OIDC_USERNAME_CLAIM:-preferred_username}"
permitted_user_match = "${RPORT_OIDC_PERMITTED_USER_MATCH:-.*}"
EOF
  echo "    Wrote: Server/Config/rportd.conf (with [plus-oauth] -> ${_ISSUER_BASE})"
  echo "      authorize_url = ${OIDC_AUTHZ}"
  echo "      token_url     = ${OIDC_TOKEN}"
  echo "      jwks_url      = ${OIDC_JWKS}"
else
  echo "    Wrote: Server/Config/rportd.conf"
fi

# ── pairing config.toml ────────────────────────────────────────────────────
PAIRING_CONF="${ROOT}/Pairing/Config/config.toml"
cat > "$PAIRING_CONF" <<EOF
# Generated by GenerateConfig.sh - do not edit manually.
[server]
  address = "0.0.0.0:${PAIRING_INTERNAL_PORT}"
  url     = "${PAIRING_URL}"
EOF
echo "    Wrote: Pairing/Config/config.toml"

# ── UI runtime env (informational; baked into image at build) ─────────────
UI_RUNTIME="${ROOT}/UI/runtime.env"
cat > "$UI_RUNTIME" <<EOF
# Generated by GenerateConfig.sh - sourced into UI container at runtime.
NUXT_PUBLIC_API_URL=${SERVER_URL}
NUXT_APP_BASE_URL=${UI_BASE}
EOF
echo "    Wrote: UI/runtime.env"

echo ""
echo "==> Config generation complete."
